### ISSUE TITLE
`ProfessorCourse.recent_semester` is confusing, change it to something else 

### ISSUE THREAD

**Issue by nsandler1** [planetterp/PlanetTerp#106]
the `recent_semester` column of the ProfessorCourse model serves a different purpose than what the name implies. All this name does is confuse anyone who looks at it. Since this column simply stores the semester that a professor taught a course, I suggest we change it to `semester_taught`. 

Anyone who decides to tackle this will need to do the following: 
- change the column name in models.py
- from the project's root directory, run `python3 manage.py makemigrations` and `python3 manage.py migrate`. Don't forget to commit the migration file!
- then change all occurrences of  `recent_semester` to the new name

**Comment by tybug** [comment]
Since this is under the `ProfessorCourse` model, `semester` would work (the "taught" is implied). But I'm fine with `semester_taught` as well. Certainly a huge step up from `recent_semester` either way.
