### ISSUE TITLE
Float "Forgot Password" button to the right 

### ISSUE THREAD

**Issue by nsandler1** [planetterp/PlanetTerp#127]
Currently, the "Forgot Password" button is right on top of the "login" button which can create a poor user experience by accidentally clicking one when trying to click the other. This can be fixed by changing the CSS property of the button to float right.

![image](https://github.com/planetterp/PlanetTerp/assets/37155082/147eb27f-875f-4ed6-beb6-aeedbcc9ae99)

**Comment by tymnec** [comment]
Assign this to me!

**Comment by nsandler1** [comment]
We're not doing explicit assignments so feel free to jump into it!
