### ISSUE TITLE
What happened to Plan-It Terp?

### ISSUE THREAD

**Issue by schance995** [planetterp/PlanetTerp#13]
Looks like the schedule builder is gone: https://planetterp.com/schedule/new

**Comment by tybug** [comment]
We decided to drop it for now as moving it over to django would have required a pretty big rewrite of the scheduler. It may return in the future if we (or someone else) ever put in the work to reimplement it.

**Comment by tybug** [comment]
going to close this in favor of https://github.com/planetterp/PlanetTerp/issues/14
