### ISSUE TITLE
"Professor boxes" in dark mode are not compliant

### ISSUE THREAD

**Issue by aco4** [planetterp/PlanetTerp#142]
Dark mode works really well! But there's only one thing holding me back from using it:

![planet terp in dark mode](https://github.com/planetterp/PlanetTerp/assets/53398545/44ba44c7-5686-4ec8-afb5-dac651bcc20b)

As you can see, the "professor boxes" aren't dark mode compliant.

**Comment by tybug** [comment]
there's a few places where darkmode is lacking...but agreed that this is one of the more egregious ones.
