### ISSUE TITLE
Increase increment speed of course grades on home page

### ISSUE THREAD

**Issue by kandasamyc** [planetterp/PlanetTerp#156]
On the home page, we display some statistics about Planetterp, including the number of course grades. This number has increased significantly over time, and so now, when the animation runs on page load, it takes a while to finish. Ideally, we increase it's speed so it finishes around the time of the other stats.

**Comment by MoheEdeen** [comment]
Ill take a look at this one and implement it!

**Comment by MoheEdeen** [comment]
https://github.com/planetterp/PlanetTerp/assets/86363939/fd4fc19e-27d4-485d-8557-4e65830b5863

**Comment by kandasamyc** [comment]
Looks good to me! Feel free to make a PR.
