### ISSUE TITLE
Certain parts of API are broken

### ISSUE THREAD

**Issue by liamc1011** [planetterp/PlanetTerp#16]
I'm getting a HTTP 500 error when trying to access certain endpoints of the Planetterp API 
The ones that seem to be broken are:
- /professor
- /professors
- /grades

All other endpoints seem to be working fine.

**Comment by tybug** [comment]
should be fixed, give it a try now.

**Comment by liamc1011** [comment]
Thanks for the quick response! The /grades endpoint is working now, but requires the semester to be specified. 
The API documentation says that semester does not need to be specified because the default is all semesters. 
Is there a specific string I need to specify to get all semesters or are more fixes required?

**Comment by tybug** [comment]
nope, just messed up the previous fix. give it a second try?

**Comment by liamc1011** [comment]
Yup it works! Thanks so much for the quick response :)
