### ISSUE TITLE
Unintended Behavior for Get Grades?

### ISSUE THREAD

**Issue by liamc1011** [planetterp/PlanetTerp#17]
I queried the Planetterp API at the /grades endpoint, supplying the name of a course and a professor. According to the docs, this should give me back grade data for the specified course taught by the specified professor, however I am getting back grade data for all courses taught by the specified professor. 

ex. [https://planetterp.com/api/v1/grades?course=CMSC131&professor=Fawzi%20Emad](https://planetterp.com/api/v1/grades?course=CMSC131&professor=Fawzi%20Emad) returns grade data for all courses Fawzi Emad has taught, rather than just grade data for CMSC131 taught by Fawzi Emad.

**Comment by tybug** [comment]
should be closed by https://github.com/planetterp/PlanetTerp/commit/e8e0a658201048a597aba494e9e34c47e7f659d7

**Comment by tybug** [comment]
going to close as fixed, please report back if you find any more issues (and thanks for the issues you have opened)

**Comment by liamc1011** [comment]
great, thanks!
