### ISSUE TITLE
Include `review.id` for admins in the information column of review tables

### ISSUE THREAD

**Issue by nsandler1** [planetterp/PlanetTerp#68]

**Comment by kandasamyc** [comment]
Hey, I'm interested in taking a shot at this as a good first issue! I went ahead and set everything up/looked into the code and wanted to know if this looked alright:
![image](https://user-images.githubusercontent.com/35542397/220439470-c32bba24-0432-4c73-89f9-02e5518911b5.png)

Is there a different format that would be better?

**Comment by tybug** [comment]
Looks good to me. The reviews are getting pretty tall, but I can't see a better place to put the id. I would probably move the id to the bottom though.

**Comment by kandasamyc** [comment]
Here's what that looks like:
![image](https://user-images.githubusercontent.com/35542397/220446480-bc035c22-08ac-434e-9420-b9d0efef50da.png)

**Comment by tybug** [comment]
looks good, feel free to pr!
