### ISSUE TITLE
Logging in/out should return the user to the page they were on, not the homepage

### ISSUE THREAD

**Issue by nsandler1** [planetterp/PlanetTerp#73]

**Comment by kandasamyc** [comment]
Here's the behavior I currently have to fix this:

_Log In_
1. User clicks login/register - this adds a url param called next with their current path
2. They're now on the login page and succesfully login
3. Once they do, they're redirected back to wherever next is

_Log out_
1. User clicks logout - button adds a next param to the request that causes the server to redirect back to the same page on logout
2. They're back on the same page, just logged out

Does that work?

**Comment by tybug** [comment]
yep, looks good. agree with using `?next` to achieve this.
